name: vps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: namespace-profile-runner1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run VPS
        run: curl -sSf https://sshx.io/get | sh -s run
